typography_spectrum: 0.28562898468226194
color:
  brandColors:
    - '#ffffff'
    - '#1d1818'
    - '#1d6075'
    - '#8eafba'
    - '#c3cbd6'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.20870177424512804
analytics:
  google: UA-35858665-1
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cb3c51d3-96c0-4959-b399-7bb57eeaaa03.png
name: Public Speaking Made-Simple
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c2ff49c3-f035-472b-9805-07ee1ab06d29.png
title: ''
purpose: []
