name: sparkwords
favicon: null
layout_spectrum: 0.18398
typography_spectrum: 0.43986
title: Sparkwords
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1e4d67'
    - '#95b836'
    - '#05171f'
    - '#62818f'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
