name: sparkwords
favicon: null
layout_spectrum: 0.11594
typography_spectrum: 0.15907
title: Sparkwords
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-35858665-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d1818'
    - '#1d6075'
    - '#8eafba'
    - '#c3cbd6'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0
purpose: []
