name: sparkwords
favicon: null
layout_spectrum: 0.48001
typography_spectrum: 0.43986
title: Think Better
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1e4d67'
    - '#95b836'
    - '#05171f'
    - '#62818f'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
