name: sparkwords
favicon: null
layout_spectrum: 0.1221903886180371
typography_spectrum: 0.11759405490010977
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07726834830828011
  lightness: 0.9444933412596583
  saturation: 0.14935872820205986
  rhythmicContrast: 0.09492827975191176
purpose: []
