typography_spectrum: 0.28562898468226194
color:
  brandColors:
    - '#ffffff'
    - '#1d1818'
    - '#1d6075'
    - '#8eafba'
    - '#c3cbd6'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.20870177424512804
analytics:
  google: UA-35858665-1
  facebook: null
  twitter: null
name: Sparkwords
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
purpose: []
