layout_spectrum: 0.444532637251541
typography_spectrum: 0.9207679782994092
color:
  brandColors:
    - '#3E454C'
    - '#2185C5'
    - '#7ECEFD'
    - '#FFF6E5'
    - '#FF7F66'
  brandStrength: 0.44508211174979806
  lightness: 0.8358385148458183
  saturation: 0.14975340035744011
  rhythmicContrast: 0.21805085218511522
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-35858665-1
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cb3c51d3-96c0-4959-b399-7bb57eeaaa03.png
name: Public Speaking Made-Easy
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c2ff49c3-f035-472b-9805-07ee1ab06d29.png
title: ''
purpose: []
