name: sparkwords
favicon: null
layout_spectrum: 0.34397
typography_spectrum: 0.15907
title: Sparkwords
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-35858665-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#95b836'
    - '#b0bbc0'
    - '#315f72'
    - '#102c4d'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
