name: sparkwords
favicon: null
layout_spectrum: 0
typography_spectrum: 0.43986
title: Sparkwords
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#95b836'
    - '#b0bbc0'
    - '#315f72'
    - '#102c4d'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
